### ISSUE TITLE
Error 2 with ubuntu Xenial build

### ISSUE THREAD

**Issue by debragail** [projectcalico/node#113]
Trying to compile a binary.  Unsuccessful on Mac OSX Yosemite with and Error 1.  Blamed it on docker toolbox since docker doesn't support 10.10.5 so they recommend the toolbox legacy version.  So I spun up a Xenial Ubuntu on EC2 instance to try to do the compile and got the following error:

```command-line-arguments
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x64d236, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc028000000, 0x4000000, 0x7fcfd8)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x7e4560, 0x4000000, 0x7f41c0023bb0, 0xc00003de58)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x7e4560, 0xf, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x7e4560, 0xf, 0x7fcfe8, 0x20300900000000)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x7e4560, 0xf, 0x410101, 0x7f41c02ece00)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x7e4560, 0xf, 0xc000000101, 0x415775)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x1e000, 0x450100, 0x7f41c3af9000)
	/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc01233df10 sp=0xc01233df08 pc=0x454b90
runtime.mallocgc(0x1e000, 0x0, 0xc01233e000, 0x4eb749)
	/usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc01233dfb0 sp=0xc01233df10 pc=0x40bb56
runtime.growslice(0x5fe720, 0xc027fde000, 0x18000, 0x18000, 0x18001, 0x4111f1, 0x18000, 0x17ffc)
	/usr/local/go/src/runtime/slice.go:197 +0x219 fp=0xc01233e018 sp=0xc01233dfb0 pc=0x4403c9
cmd/link/internal/sym.(*Symbol).AddUint8(...)
	/usr/local/go/src/cmd/link/internal/sym/symbol.go:106
cmd/link/internal/ld.putpclcdelta(0xc0004d6000, 0x6855a0, 0xc0004d6000, 0xc027e5db70, 0x20, 0xfffffffffffffe54)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:1044 +0x235 fp=0xc01233e0b8 sp=0xc01233e018 pc=0x550285
cmd/link/internal/ld.writelines(0xc0004d6000, 0xc0000549c0, 0xc000f4a000, 0x4bf, 0x6a0, 0xc027e5db70, 0xc027e5dc48, 0xc009b62600, 0x15, 0x20, ...)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:1289 +0x1603 fp=0xc01233e5e8 sp=0xc01233e0b8 pc=0x552523
cmd/link/internal/ld.dwarfgeneratedebugsyms(0xc0004d6000)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:1764 +0x97f fp=0xc01233e7d0 sp=0xc01233e5e8 pc=0x55790f
cmd/link/internal/ld.(*Link).dodata(0xc0004d6000)
	/usr/local/go/src/cmd/link/internal/ld/data.go:1585 +0x3344 fp=0xc01233ece8 sp=0xc01233e7d0 pc=0x53d344
cmd/link/internal/ld.Main(0x7d1c20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64edf0, 0x1b, 0x64bf34, 0x14, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:232 +0xb44 fp=0xc01233ee80 sp=0xc01233ece8 pc=0x5833f4
main.main()
	/usr/local/go/src/cmd/link/main.go:65 +0x227 fp=0xc01233ff98 sp=0xc01233ee80 pc=0x5db527
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc01233ffe0 sp=0xc01233ff98 pc=0x42bae7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc01233ffe8 sp=0xc01233ffe0 pc=0x456af1
Makefile:225: recipe for target 'dist/bin//calico-node-amd64' failed
make: *** [dist/bin//calico-node-amd64] Error 2

**Comment by caseydavenport** [comment]
@debragail how much memory does the machine you're using have? Looks like the build is running out.

**Comment by debragail** [comment]
This is what happens with make test

```
root@ip-172-31-87-56:/home/ubuntu/evolute/node# make test
"Build dependency versions"
BIRD_VER              = v0.3.3-0-g1e8dd375
"Test dependency versions"
CNI_VER               = master    
"Calico git version"
CALICO_GIT_VER        = v3.5.0-0.dev-5-g335914a
Error: No such container: st-apiserver
Makefile:387: recipe for target 'stop-k8s-apiserver' failed
make: [stop-k8s-apiserver] Error 1 (ignored)
Error: No such container: calico-etcd
Makefile:343: recipe for target 'run-etcd' failed
make: [run-etcd] Error 1 (ignored)
docker run --detach \
--net=host \
--name calico-etcd quay.io/coreos/etcd:v3.3.7 \
etcd \
--advertise-client-urls "http://172.31.87.56:2379,http://127.0.0.1:2379" \
--listen-client-urls "http://0.0.0.0:2379"
Unable to find image 'quay.io/coreos/etcd:v3.3.7' locally
v3.3.7: Pulling from coreos/etcd
ff3a5c916c92: Pull complete 
78a2c8b9112d: Pull complete 
f3c8c402ad97: Pull complete 
de364b4ae594: Pull complete 
017130412210: Pull complete 
a921ab36ed1e: Pull complete 
Digest: sha256:94cca04c1e8bf534dc1f8638317cbd53af17aa8dcc8a127e6e058eeae450f853
Status: Downloaded newer image for quay.io/coreos/etcd:v3.3.7
a577a1d06c64b74db6a62ce137bc6a61475a1d52fa641d87d3cfc9682b6c1944
docker run \
	--net=host --name st-apiserver \
	-v  /home/ubuntu/evolute/node/vendor/github.com/projectcalico/libcalico-go/test/:/manifests \
	--detach \
	gcr.io/google_containers/hyperkube-amd64:v1.11.3 \
	/hyperkube apiserver \
		--bind-address=0.0.0.0 \
		--insecure-bind-address=0.0.0.0 \
			--etcd-servers=http://127.0.0.1:2379 \
		--admission-control=NamespaceLifecycle,LimitRanger,DefaultStorageClass,ResourceQuota \
		--authorization-mode=RBAC \
		--service-cluster-ip-range=10.101.0.0/16 \
		--v=10 \
		--logtostderr=true
Unable to find image 'gcr.io/google_containers/hyperkube-amd64:v1.11.3' locally
v1.11.3: Pulling from google_containers/hyperkube-amd64
d093dc0d702b: Pull complete 
0dc0248c9360: Pull complete 
2b6ac55109de: Pull complete 
5f2ca80930ac: Pull complete 
c99d41457802: Pull complete 
7460c29cea53: Pull complete 
fec6a0197cb8: Pull complete 
f7d771a81aa1: Pull complete 
Digest: sha256:f6ec5bb2e12ac585d58c14c6d7f08092244594fb4224551cabcffabdecf9d4ba
Status: Downloaded newer image for gcr.io/google_containers/hyperkube-amd64:v1.11.3
edf56375d8a7651275c0e0173beccf2086132ae338f312f5de1f2564faa4caca
# Wait until we can configure a cluster role binding which allows anonymous auth.
while ! docker exec st-apiserver kubectl create \
	clusterrolebinding anonymous-admin \
	--clusterrole=cluster-admin \
	--user=system:anonymous; \
	do echo "Trying to create ClusterRoleBinding"; \
	sleep 1; \
	done
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Trying to create ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/anonymous-admin created
# Create CustomResourceDefinition (CRD) for Calico resources
# from the manifest crds.yaml
while ! docker exec st-apiserver kubectl \
	apply -f /manifests/crds.yaml; \
	do echo "Trying to create CRDs"; \
	sleep 1; \
	done
customresourcedefinition.apiextensions.k8s.io/globalfelixconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalbgpconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
docker run --rm \
-v /home/ubuntu/evolute/node:/go/src/github.com/projectcalico/node:rw \
 \
-e LOCAL_USER_ID=0 \
-e ETCD_ENDPOINTS=http://172.31.87.56:2379 \
--net=host \
-w /go/src/github.com/projectcalico/node \
calico/go-build:v0.20 ginkgo -cover -r -skipPackage vendor pkg/startup pkg/allocateipip 
Starting with UID : 0
adduser: uid '0' in use
Failed to compile startup:

# github.com/projectcalico/node/pkg/startup.test
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x64d236, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc014000000, 0x4000000, 0x7fcfd8)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x7e4560, 0x4000000, 0x7f3e7d831950, 0x7ffc5946d348)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x7e4560, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x7e4560, 0x8, 0x7fcfe8, 0x20300400000000)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x7e4560, 0x8, 0x410101, 0x7f3e7da4e800)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x7e4560, 0x8, 0x7ffc59010101, 0x415775)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0xfc3d, 0x450101, 0x7f3e805ef000)
	/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x454a99)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000534148 sp=0xc000534140 pc=0x454b90
runtime.mallocgc(0xfc3d, 0x5fe720, 0xc000534401, 0xfc3d)
	/usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc0005341e8 sp=0xc000534148 pc=0x40bb56
runtime.makeslice(0x5fe720, 0xfc3d, 0xfc3d, 0x8, 0x600f20, 0x33f)
	/usr/local/go/src/runtime/slice.go:70 +0x77 fp=0xc000534218 sp=0xc0005341e8 pc=0x440127
cmd/link/internal/objfile.(*objReader).readSlices(0xc0005344f0)
	/usr/local/go/src/cmd/link/internal/objfile/objfile.go:140 +0x49 fp=0xc000534260 sp=0xc000534218 pc=0x516f89
cmd/link/internal/objfile.(*objReader).loadObjFile(0xc0005344f0)
	/usr/local/go/src/cmd/link/internal/objfile/objfile.go:113 +0x41e fp=0xc000534448 sp=0xc000534260 pc=0x516ace
cmd/link/internal/objfile.Load(0x7d1c20, 0xc00005c0a0, 0xc0114e7260, 0xc00a70fd40, 0x29b2d, 0xc013f655e0, 0x63)
	/usr/local/go/src/cmd/link/internal/objfile/objfile.go:69 +0x1c4 fp=0xc000534618 sp=0xc000534448 pc=0x5164c4
cmd/link/internal/ld.ldobj(0xc0004d4000, 0xc0114e7260, 0xc00a70fd40, 0x29b99, 0xc013f655e0, 0x63, 0xc0004f9f70, 0x5b, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1549 +0xc90 fp=0xc0005348d0 sp=0xc000534618 pc=0x573790
cmd/link/internal/ld.loadobjfile(0xc0004d4000, 0xc00a70fd40)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:846 +0x4d9 fp=0xc000534a88 sp=0xc0005348d0 pc=0x56ce19
cmd/link/internal/ld.(*Link).loadlib(0xc0004d4000)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:361 +0x16a fp=0xc000534ce8 sp=0xc000534a88 pc=0x5696ea
cmd/link/internal/ld.Main(0x7d1c20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64edf0, 0x1b, 0x64bf34, 0x14, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:207 +0xa2d fp=0xc000534e80 sp=0xc000534ce8 pc=0x5832dd
main.main()
	/usr/local/go/src/cmd/link/main.go:65 +0x227 fp=0xc000535f98 sp=0xc000534e80 pc=0x5db527
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000535fe0 sp=0xc000535f98 pc=0x42bae7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000535fe8 sp=0xc000535fe0 pc=0x456af1

Ginkgo ran 1 suite in 2m16.95476271s
Test Suite Failed
Makefile:331: recipe for target 'fv' failed
make: *** [fv] Error 1

**Comment by debragail** [comment]
> @debragail how much memory does the machine you're using have? Looks like the build is running out.

I'm running a tier 2 micro instance so it's 1 G of memory.

**Comment by caseydavenport** [comment]
@debragail that sounds like it's probably the issue - try using an instance with more memory.

**Comment by debragail** [comment]
yah that worked thanks!  I was able to build kube-controller but must have not been as heavy.

> @debragail that sounds like it's probably the issue - try using an instance with more memory.

**Comment by caseydavenport** [comment]
glad it worked!

And yeah, the kube-controllers build is a tad bit simpler than building node.
