### ISSUE TITLE
table.go 658: iptables save failed error=exit status 1

### ISSUE THREAD

**Issue by KylanZhang** [projectcalico/node#379]
iptables-save failed by using calico node on k8s 1.15.x.
os: centos 7.5
iptables: v1.4.21
calico node: 3.7.5

## Context

**calico node log:**
2019-12-02 09:10:53.880 [INFO][31117] ipsets.go 356: Finished resync family="inet6" numInconsistenciesFound=0 resyncDuration=3.765228ms
2019-12-02 09:10:53.881 [INFO][31117] ipsets.go 749: Doing full IP set rewrite family="inet6" numMembersInPendingReplace=1 setID="all-ipam-pools"
2019-12-02 09:10:53.881 [INFO][31117] ipsets.go 749: Doing full IP set rewrite family="inet6" numMembersInPendingReplace=0 setID="masq-ipam-pools"
2019-12-02 09:10:53.881 [INFO][31117] ipsets.go 749: Doing full IP set rewrite family="inet6" numMembersInPendingReplace=3 setID="this-host"
2019-12-02 09:10:53.882 [INFO][31117] ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=5.020537ms
2019-12-02 09:10:53.882 [INFO][31117] ipsets.go 749: Doing full IP set rewrite family="inet" numMembersInPendingReplace=1 setID="all-ipam-pools"
2019-12-02 09:10:53.883 [INFO][31117] ipsets.go 749: Doing full IP set rewrite family="inet" numMembersInPendingReplace=1 setID="masq-ipam-pools"
2019-12-02 09:10:53.883 [INFO][31117] ipsets.go 749: Doing full IP set rewrite family="inet" numMembersInPendingReplace=5 setID="this-host"
2019-12-02 09:10:53.978 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x6 table="raw"
2019-12-02 09:10:54.076 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x6 table="nat"
2019-12-02 09:10:54.077 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.077 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="raw"
2019-12-02 09:10:54.077 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x4 table="mangle"
2019-12-02 09:10:54.078 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.079 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="nat"
2019-12-02 09:10:54.176 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x6 table="mangle"
2019-12-02 09:10:54.178 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x4 table="nat"
2019-12-02 09:10:54.179 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.179 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="mangle"
2019-12-02 09:10:54.275 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.275 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="raw"
2019-12-02 09:10:54.277 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x4 table="raw"
2019-12-02 09:10:54.375 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.375 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="nat"
2019-12-02 09:10:54.376 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x4 table="filter"
2019-12-02 09:10:54.378 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.378 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="mangle"
2019-12-02 09:10:54.378 [INFO][31117] table.go 465: Loading current iptables state and checking it is correct. ipVersion=0x6 table="filter"
2019-12-02 09:10:54.478 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.478 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="filter"
2019-12-02 09:10:54.479 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.479 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="raw"
2019-12-02 09:10:54.578 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.579 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="nat"
2019-12-02 09:10:54.581 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.581 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="mangle"
2019-12-02 09:10:54.581 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.581 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="filter"
2019-12-02 09:10:54.785 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.785 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="filter"
2019-12-02 09:10:54.882 [WARNING][31117] table.go 658: iptables save failed error=exit status 1
2019-12-02 09:10:54.882 [WARNING][31117] table.go 607: ip6tables-save command failed error=exit status 1 ipVersion=0x6 stderr="" table="raw"
2019-12-02 09:10:54.882 [PANIC][31117] table.go 613: ip6tables-save command failed after retries ipVersion=0x6 table="raw"
panic: (*logrus.Entry) (0x1969ce0,0xc000744320)

goroutine 266 [running]:
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000e20a0, 0xc000718720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:128 +0x5a8
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc0005260f0, 0xc000517890, 0x1, 0x1)
	/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:173 +0xb2
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.(*Entry).Panicf(0xc0005260f0, 0x19cfbb5, 0x1f, 0xc000517920, 0x1, 0x1)
	/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:221 +0xed
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables.(*Table).getHashesAndRulesFromDataplane(0xc000746600, 0x6aa5b835, 0x2b12480)
	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables/table.go:613 +0x2b5
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables.(*Table).loadDataplaneState(0xc000746600)
	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables/table.go:467 +0x142
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables.(*Table).Apply(0xc000746600, 0xc0001e25a0)
	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables/table.go:825 +0x975
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func3(0xc00029eaa0, 0xc00029eaa8, 0xc00029f110, 0xc000746600)
	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:1110 +0x2f
created by github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply

## Your Environment

* calico/node version: 3.7.5
* Operating System and version: centos 7.5
* Link to your project (optional):

**Comment by tmjd** [comment]
Is this something that is repeatedly happening or after node restarts it clears?
Are there a large number of services in the cluster this is happening in?
Is selinux enabled on your hosts? I haven't seen this error before but wondering if somehow it is preventing some manipulation.
You could try setting the log level for calico-node to debug to see if there are any additional logs that suggest the root of the problem.

**Comment by KylanZhang** [comment]
@tmjd  This is the first install。But, when I restart all VMs, the error log are not appear on all nodes.
